### ISSUE TITLE
clean_date() throws ValueError

### ISSUE THREAD

**Issue by FabianPalmaPando** [sfu-db/dataprep#749] opened 2021-11-18 17:52 UTC
Running the following 3 line code using clean_date() throws a ValueError:
---------
df=pd.DataFrame({'date':['1996.07.10 AD at 15:08:56 PDT Thu aug 30 10:36:28 2003', 'Thu Sep 25 10:36:28 BRST 2003', 'a', 1]})
clean=clean_date(df, 'date')
ValueError: invalid literal for int() with base 10: 'a'
--------
 - Python Version=3.8
 - Pandas Version=1.2.5
 - Dataprep Version=0.4.0

**Comment by qidanrui** [comment] 2021-11-18 18:10
Hi! Thank you for reporting this issue! I think it is because the initial checking didn't consider the single characters which cannot be split. We will fix this bug. Thank you~

**Comment by moreaupascal56** [comment] 2021-11-29 11:38
Hello @qidanrui I took some time to look about this, the error come from the fact that `"a"` is in the AM flags `AM = ["AM", "am", "a"]` ([clean_date_utils](https://github.com/sfu-db/dataprep/blob/4032acb1d1f2c413d4cb000d17e8ffa611315f9f/dataprep/clean/clean_date_utils.py#L73)). 

Indeed it is not an error because 'a' is a single charachter string because the function is working if you try with another 1 char string ('b' for example) in this case the function `def clean_date` [(link)](https://github.com/sfu-db/dataprep/blob/4032acb1d1f2c413d4cb000d17e8ffa611315f9f/dataprep/clean/clean_date.py#L45) will return `unknown` and `clean_date()` returns NaN

AS "a" is in the  AM flag list,  the date is considered `cleaned` in `def check_date` [(link)](https://github.com/sfu-db/dataprep/blob/4032acb1d1f2c413d4cb000d17e8ffa611315f9f/dataprep/clean/clean_date_utils.py#L590) which result in error because 'a' is a string and not an  integer in `ensure_pm` function where `hms_tokens` parameter will be in this case  `hms_tokens=['a']` which is causing the Error  [line 784](https://github.com/sfu-db/dataprep/blob/4032acb1d1f2c413d4cb000d17e8ffa611315f9f/dataprep/clean/clean_date.py#L784) `parsed_data.set_hour(int(hms_tokens[0]) + offset)`. 

By the way you can reproduce the error by putting as input date every AM or PM flag (for example just "AM" as an input date). 

I have think about some idea to fix but I am not convinced:

-  maybe just consider that an input date with only an AM/PM flag is "unknown" in `check_date` ? But that's not making a lot of sense in this function...

- Or raise an error (or return NaN like it's done [here](https://github.com/sfu-db/dataprep/blob/4032acb1d1f2c413d4cb000d17e8ffa611315f9f/dataprep/clean/clean_date.py#L271)) if string tokens are passed in `ensure_hms` function.

**Closed as completed** 2022-02-15 20:45 UTC
Labels: type: bug
