### ISSUE TITLE
Connecting to the API errro: JSONDecodeError

### ISSUE THREAD

**Issue by AbeerAbuZayed** [sfu-db/dataprep#541] opened 2021-03-22 09:36 UTC
I am trying to collect data from DBLP, however, when I try to connect to the API using:
```python
conn = connect("dblp")
```
I get this error:
```python

JSONDecodeError: Extra data: line 1 column 4 (char 3)
```

 - Platform [Google Colab]

**Comment by peiwangdb** [comment] 2021-03-22 17:34
Hi @AbeerAbuZayed thanks a lot for trying out our tool! 
The issue is because we are doing an upgrading now. 
By calling connect(), the library access the config repo there https://github.com/sfu-db/APIConnectors and download the file to the local temporary folder. We changed the name of the repo very recently so there is an error. 
This will be resolved in our next release (soon).
For now, you can manually download the dblp folder from the config repo and then use it.

Let me know if you need help!

**Closed** 2021-03-23 21:18 UTC
Labels: type: bug
