### ISSUE TITLE
dataprep plot() doesn't show plots on the Google Colab interface.

### ISSUE THREAD

**Issue by manjum2050** [sfu-db/dataprep#102] opened 2020-03-16 00:54 UTC
I used dataprep on google colab for one  of my EDA work. The dataprep library works well on google colab but doesn't shows up the plots.

**Comment by brandonlockhart** [comment] 2020-06-14 20:04
This issue has been raised again today in a comment on our blog post. I'm getting this error on Colab:

![Screen Shot 2020-06-14 at 12 48 40 PM](https://user-images.githubusercontent.com/25874021/84602630-c20b9b00-ae3d-11ea-8ad2-27f345d92bdc.png)

**Comment by peterirani** [comment] 2020-06-15 17:19
Hi Brandon and Young, I would like to work on this issue, if no one else is already working on it.

**Comment by peterirani** [comment] 2020-06-23 01:45
Hi Brandon and Young, for the clearing the cache issue for the plot(df), it looks like it is a CORS issue that specific to Bokeh running on Chrome (https://github.com/bokeh/bokeh/issues/9773). 

The plot(df) function worked well in the local Jupyter notebook using **Safari**. However the google colab error still exists in Safari. 

For **NON-dataprep bokeh gridplots** were again not being display in Chrome (it threw the CORS policy error again unless you clear the cache), when I changed the browser to safari it worked again.

**Code for Chrome:**
![Screen Shot 2020-06-22 at 6 38 23 PM](https://user-images.githubusercontent.com/59293179/85351162-e6a7e880-b4b7-11ea-9bf2-67a62e5992ac.png)

**Error on Chrome:**
![Screen Shot 2020-06-22 at 6 38 09 PM](https://user-images.githubusercontent.com/59293179/85351178-f45d6e00-b4b7-11ea-852f-a88c5e3dcb6a.png)

**Slightly modified code for Safari:**
![Screen Shot 2020-06-22 at 6 38 45 PM](https://user-images.githubusercontent.com/59293179/85351205-03442080-b4b8-11ea-8bac-8748be51a41e.png)

**Result on Safari:**
![Screen Shot 2020-06-22 at 6 38 37 PM](https://user-images.githubusercontent.com/59293179/85351237-1656f080-b4b8-11ea-8cb0-71af16a1be56.png)

**Comment by jnwang** [comment] 2020-06-23 16:58
It seems that the issue was fixed in bokeh-2.1. I cannot test it since dataprep 0.2.6 has requirement bokeh<2.1,>=2.0, which is incompatible with bokeh 2.1.1. @dovahcrow @brandonlockhart

**Comment by brandonlockhart** [comment] 2020-07-01 18:57
@peterirani and I are getting an error in Colab with dataprep version 0.2.7. Code to reproduce:
``` python
# install
!pip install dataprep
pip install -U ipykernel

from dataprep.eda import plot
import seaborn as sbn
df = sbn.load_dataset('iris')
plot(df)
```
Error from the console output:
Bokeh: ERROR: Unable to run BokehJS code because BokehJS library is missing
@dovahcrow

**Comment by bhishanpdl** [comment] 2020-07-06 15:54
Date: Jul 6, 2020

I am experiencing a similar problem in gcolab.

# Versions
```
bokeh 2.1.1
dataprep 0.2.8
tornado 6.0.4
```

# MWE:
```python
!pip install -U tornado
!pip install dataprep

import time,os,json
import numpy as np
import pandas as pd
import seaborn as sns

import dataprep.eda as de
import bokeh.io
bokeh.io.output_notebook()

df = sns.load_dataset('titanic')
de.plot(df) # this gives nothing, does not give error but does not give any outputs.

# another attempt
from dataprep.eda import plot
plot(df) # gives no output
```

**Comment by korakot** [comment] 2020-07-07 04:56
After a lot of hacking (reading) into the code. Here's how to display plot in Colab.

```python
def _report_repr_html_(self):
    from bokeh.io.notebook import load_notebook
    from bokeh.embed.notebook import notebook_content
    from IPython.display import publish_display_data

    load_notebook(hide_banner=True)
    (script, div, cell_doc) = notebook_content(self.to_render)
    return f'{div}<script>{script}</script>'

from dataprep.eda.report import Report
Report._repr_html_ = _report_repr_html_
```

Now your minimal example `plot(df)` should work.

**Comment by jnwang** [comment] 2020-07-07 05:36
Thank you @korakot !! Would you like to submit a [PR](https://github.com/sfu-db/dataprep/wiki/Steps-to-a-successful-PR)? We can put it in the next release cycle (in ~10 days).

**Comment by korakot** [comment] 2020-07-07 06:20
@jnwang I use Colab exclusively. So, I cannot test with other environment. Hope the minimal change doesn't impact other code.

Here's [my PR](https://github.com/sfu-db/dataprep/pull/220)

**Comment by jnwang** [comment] 2020-07-07 06:27
Thank you!! No worries. We will do extensive testing. :)

**Closed** 2020-07-13 22:22 UTC
Labels: module: EDA, type: bug
